
services:
  server:
    build: ./Server 
    ports:
      - "3000:3000" 
    volumes:
      - ./Server:/app 
  client:
    build: ./Client 
    ports:
      - "5173:5173" 
    volumes:
      - ./Client:/app 
